<?php

/**
 * Copyright Maarch since 2008 under licence GPLv3.
 * See LICENCE.txt file at the root folder for more details.
 * This file is part of Maarch software.
 */

/**
 * @brief Lang English
 *
 * @author dev@maarch.org
 */

$lang = [
    'actionDone'                                => 'Action done',
    'attachmentAdded'                           => 'Attachment added',
    'attachmentViewed'                          => 'Attachment viewed',
    'configurationUpdated'                      => 'Configuration modifié',
    'documentAdded'                             => 'Document added',
    'documentViewed'                            => 'Document viewed',
    'documentHistoryViewed'                     => 'Document history viewed',
    'processedDocumentViewed'                   => 'Processed document viewed',
    'emailAdded'                                => 'Email added',
    'emailNoSubject'                            => 'No subject',
    'emailFailed'                               => 'Sending email failed',
    'notificationDocumentAddedSubject'          => '[Maarch Parapheur] Notification       ',
    'notificationDocumentAddedBody'             => 'A document has been sent to you on Maarch Parapheur.<br/>Click on the link below to consult it :<br/>',
    'notificationFooter'                        => '<br/><br/>This email is automatically generated by Maarch Parapheur.<br/>If you don\'t want to receive these notifications, mark it on your profile.',
    'notificationForgotPasswordSubject'         => '[Maarch Parapheur] Reset password informations',
    'notificationForgotPasswordBody'            => 'Hello,<br/>You requested to reset the password for your Maarch Parapheur account.<br/>To change your password, please click on the link below :<br/>',
    'notificationForgotPasswordFooter'          => '<br/><br/>If you did not perform this request, you can safely ignore this email.<br/>Please contact your administrator if you have any questions.',
    'UserLogIn'                                 => 'User log in',
    'UserLogOut'                                => 'User log out',
    'userAdded'                                 => 'User added',
    'userUpdated'                               => 'User updated',
    'userPasswordUpdated'                       => 'User password updated',
    'userPasswordForgotten'                     => 'User password forgotten',
    'userForgottenPasswordUpdated'              => 'User password updated after forgot request',
    'userViewed'                                => 'User viewed',
    'userSignatureAdded'                        => 'User signature added',
    'userSignatureDeleted'                      => 'User signature deleted'
];
